# Placeholders to be rewritten by launch file:
# - <entity> : Should be replaced by entity name: For example "robot".
# - <world> : Correspond to the world name, the world name must be consistent with
#   the file name, for example, 'empty.sdf' world should be called 'empty' inside.

# Servo G-Mov
- ros_topic_name: "/g_mov_joint/cmd_pos"
  gz_topic_name: "/model/<entity>/joint/g_mov_servo_conn_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Pi cam
- ros_topic_name: "/pi_cam/image_raw"
  gz_topic_name: "/world/<world>/model/<entity>/link/servo_conn/sensor/camera_g/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/pi_cam/camera_info"
  gz_topic_name: "/world/<world>/model/<entity>/link/servo_conn/sensor/camera_g/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/imu"
  gz_topic_name: "/world/custom_empty/model/orion/link/base_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS